# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit <- function(y, X, groups, lambda, a0, b0, tau_a0, tau_b0, mu, s, g, track_elbo, track_elbo_every, track_elbo_mcn, niter, tol, verbose) {
    .Call(`_gsvb_fit`, y, X, groups, lambda, a0, b0, tau_a0, tau_b0, mu, s, g, track_elbo, track_elbo_every, track_elbo_mcn, niter, tol, verbose)
}

update_mu <- function(G, Gc, xtx, yx, mu, s, g, e_tau, lambda) {
    .Call(`_gsvb_update_mu`, G, Gc, xtx, yx, mu, s, g, e_tau, lambda)
}

update_mu_fn_2 <- function(m, xtx, yx, mu, s, g, sigma, lambda, G, Gc, mcn) {
    .Call(`_gsvb_update_mu_fn_2`, m, xtx, yx, mu, s, g, sigma, lambda, G, Gc, mcn)
}

update_s <- function(G, xtx, mu, s, e_tau, lambda) {
    .Call(`_gsvb_update_s`, G, xtx, mu, s, e_tau, lambda)
}

update_g <- function(G, Gc, xtx, yx, mu, s, g, e_tau, lambda, w) {
    .Call(`_gsvb_update_g`, G, Gc, xtx, yx, mu, s, g, e_tau, lambda, w)
}

update_a_b_obj <- function(ta, tb, ta0, tb0, S, n) {
    .Call(`_gsvb_update_a_b_obj`, ta, tb, ta0, tb0, S, n)
}

update_a_b <- function(tau_a, tau_b, tau_a0, tau_b0, S, n) {
    invisible(.Call(`_gsvb_update_a_b`, tau_a, tau_b, tau_a0, tau_b0, S, n))
}

elbo <- function(yty, yx, xtx, groups, n, p, mu, s, g, tau_a, tau_b, lambda, a0, b0, tau_a0, tau_b0, mcn, approx, approx_thresh) {
    .Call(`_gsvb_elbo`, yty, yx, xtx, groups, n, p, mu, s, g, tau_a, tau_b, lambda, a0, b0, tau_a0, tau_b0, mcn, approx, approx_thresh)
}

compute_S <- function(yty, yx, xtx, groups, mu, s, g, p, approx, approx_thresh) {
    .Call(`_gsvb_compute_S`, yty, yx, xtx, groups, mu, s, g, p, approx, approx_thresh)
}

