# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

elbo <- function(y, X, groups, mu, s, g, lambda, a0, b0, sigma, mcn) {
    .Call(`_gsvb_elbo`, y, X, groups, mu, s, g, lambda, a0, b0, sigma, mcn)
}

fit <- function(y, X, groups, lambda, a0, b0, sigma, mu, s, g, track_elbo, track_elbo_every, track_elbo_mcn, niter, tol, verbose) {
    .Call(`_gsvb_fit`, y, X, groups, lambda, a0, b0, sigma, mu, s, g, track_elbo, track_elbo_every, track_elbo_mcn, niter, tol, verbose)
}

update_mu <- function(G, Gc, xtx, yx, mu, s, g, sigma, lambda) {
    .Call(`_gsvb_update_mu`, G, Gc, xtx, yx, mu, s, g, sigma, lambda)
}

update_mu_fn_2 <- function(m, xtx, yx, mu, s, g, sigma, lambda, G, Gc, mcn) {
    .Call(`_gsvb_update_mu_fn_2`, m, xtx, yx, mu, s, g, sigma, lambda, G, Gc, mcn)
}

update_s <- function(G, xtx, mu, s, sigma, lambda) {
    .Call(`_gsvb_update_s`, G, xtx, mu, s, sigma, lambda)
}

update_g <- function(G, Gc, xtx, yx, mu, s, g, sigma, lambda, w) {
    .Call(`_gsvb_update_g`, G, Gc, xtx, yx, mu, s, g, sigma, lambda, w)
}

