# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit <- function(y, X, groups, lambda, a0, b0, tau_a0, tau_b0, mu, s, g, constrained, track_elbo, track_elbo_every, track_elbo_mcn, niter, tol, verbose) {
    .Call(`_gsvb_fit`, y, X, groups, lambda, a0, b0, tau_a0, tau_b0, mu, s, g, constrained, track_elbo, track_elbo_every, track_elbo_mcn, niter, tol, verbose)
}

update_a_b_obj <- function(ta, tb, ta0, tb0, R, n) {
    .Call(`_gsvb_update_a_b_obj`, ta, tb, ta0, tb0, R, n)
}

update_a_b <- function(tau_a, tau_b, tau_a0, tau_b0, R, n) {
    invisible(.Call(`_gsvb_update_a_b`, tau_a, tau_b, tau_a0, tau_b0, R, n))
}

elbo_c <- function(yty, yx, xtx, groups, n, p, mu, s, g, tau_a, tau_b, lambda, a0, b0, tau_a0, tau_b0, mcn, approx, approx_thresh) {
    .Call(`_gsvb_elbo_c`, yty, yx, xtx, groups, n, p, mu, s, g, tau_a, tau_b, lambda, a0, b0, tau_a0, tau_b0, mcn, approx, approx_thresh)
}

